# Generated by Django 4.1.3 on 2022-11-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
