# Generated by Django 4.1.3 on 2022-11-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_alter_ticket_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='upload',
            new_name='image',
        ),
    ]
